Lesson 2-1/Lesson 2-1/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson_2_1.Controllers
{
    public class CalcController : Controller
    {
        // GET: Calc
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add(int? x, int? y)
        {
            if (x!=null && y!=null)
            {
                ViewBag.Result = x + y;
            }
            return View();
        }
        public ActionResult Mul(int? x, int? y)
        {
            if (x!=null && y!=null)
            {
                ViewBag.X = x;
                ViewBag.Y = y;
                ViewBag.Result = x * y;
            }
            return View();
        }
        public ActionResult Sub(int? x, int? y)
        {
            if (x!=null && y!=null)
            {
                ViewBag.Result = x - y;

            }
            return View();
        }
       
    }
}

Lesson 2-1/Lesson 2-1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson_2_1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Message = "Hello";
            return View();
        }
    }
}

Lesson 2-1/Lesson 2-1/Views/Calc/Add.cshtml
@model Lesson_2_1.Controllers.CalcController
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <div> 
        <h1>Controller: Calc</h1>
        <h2>View: Add</h2>
        <h3>Result: @ViewBag.Result</h3>
    </div>
</body>
</html>

Lesson 2-1/Lesson 2-1/Views/Calc/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>Controller: CalcController</h1>
        <h2>View: Index</h2>
        @Html.ActionLink("Add result", "Add", "Calc", new { x = 10, y = 20 }, null) <br/>
        @Html.ActionLink("Mul result", "Mul", "Calc", new { x=5, y=5}, null) <br />
        @Html.ActionLink("Sub result", "Sub", "Calc", new { x = 20, y = 54 }, null)


    </div>
</body>
</html>

Lesson 2-1/Lesson 2-1/Views/Calc/Mul.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mul</title>
</head>
<body>
    <div> 
        <h1>Controller: Calc</h1>
        <h2>View: Mul</h2>
        <h3>Result: x=@ViewBag.X; y=@ViewBag.Y Result = @ViewBag.Result</h3>
    </div>
</body>
</html>

Lesson 2-1/Lesson 2-1/Views/Calc/Sub.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sub</title>
</head>
<body>
    <div> 
        <h1>Controller: Calc</h1>
        <h2>View: Sub</h2>
        <h3>Result = @ViewBag.Result</h3>
    </div>
</body>
</html>

Lesson 2-1/Lesson 2-1/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h1>Index Page</h1>        
        @Html.ActionLink("Calc Controller. Index view", "Index", "Calc")
    </div>
</body>
</html>